# Generated by Django 4.0.6 on 2022-09-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reward', '0001_initial'),
        ('userStat', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewarduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeFeedbackCreated', models.DateTimeField(auto_now=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.reward')),
                ('userStat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userStat.userstat')),
            ],
        ),
    ]
