# Generated by Django 4.0.6 on 2022-09-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userStat', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('timeDecisionMade', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(default='1', max_length=256)),
                ('question', models.IntegerField()),
                ('userStat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userStat.userstat')),
            ],
        ),
    ]
