# Generated by Django 4.0.6 on 2022-09-16 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.CharField(default=100, max_length=20)),
                ('money', models.CharField(default=100, max_length=20)),
                ('dayDeadOn', models.DateField(blank=True, null=True)),
                ('dayFinished', models.DateField(blank=True, null=True)),
                ('position', models.CharField(default=0, max_length=20)),
                ('isDead', models.BooleanField(blank=True, default=False, null=True)),
                ('isPlaying', models.BooleanField(blank=True, default=True, null=True)),
                ('didWin', models.BooleanField(blank=True, null=True)),
                ('score', models.IntegerField(default=None, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
