# Generated by Django 4.0.6 on 2022-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jeff', max_length=60)),
                ('gameStartDate', models.DateTimeField()),
                ('gameEndDate', models.DateTimeField()),
                ('isJoinable', models.BooleanField(default=True)),
            ],
        ),
    ]
